name: CI / Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --verbose > build_log.txt 2>&1
      continue-on-error: true

    - name: Commit Log
      if: matrix.os == 'windows-latest'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        copy build_log.txt windows_build_log_${{ matrix.build_type }}.txt
        git add windows_build_log_${{ matrix.build_type }}.txt
        git commit -m "Upload build log ${{ matrix.build_type }}"
        git pull --rebase
        git push

    - name: Run Tests
      working-directory: build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
